// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alkclooagwvogugmdxko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsa2Nsb29hZ3d2b2d1Z21keGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDQ4ODQsImV4cCI6MjA2MjYyMDg4NH0.lIpXxuhIj6arX5PTtqbvwFO34gRTMkQg9XbYdHhlzOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);